export * from './auth.api';
export * from './categories.api';
export * from './products.api';
export * from './sliders.api';
export * from './upload.api';
export * from './user.api';
export * from './color.api';
export * from './brand.api';
export * from './order.api';
